.ORIG x3000

;;YOUR CODE STARTS HERE

AND R0, R0, #0;STRING
AND R1, R1, #0;ASCII OFFSET
AND R2, R2, #0;CHECK NUM
AND R3, R3, #0;VALUE
AND R4, R4, #0;CHECK *
AND R5, R5, #0;
AND R6, R6, #0;ADDRESS BEGIN
AND R7, R7, #0;ADDRESS END


LD R0, STRING_START
READ	LDR R3, R0, #0
	LD R1, ASCII_NEG_ZERO
	AND R2, R2, #0	
	ADD R2, R3, R2	
	ADD R2, R1, R2
	BRzp NUMORLET
	BRn SIGN


NUMORLET	ADD R6, R0, R6
		LD R1, ASCII_NINE
		NOT R1, R1
		ADD R1, R1, #1
		AND R2, R2, #0		
		ADD R2, R3, R2
		ADD R2, R1, R2
		BRp READ ; LETTER
		BRnz TRAVERSE

	
SIGN	LD R1, ASCII_NEG_ASTERISK
	AND R4, R4, #0	
	ADD R4, R3, R4
	ADD R4, R1, R4
	BRn DONE
	BRzp CONTINUE_AST


TRAVERSE	
							
		

LOOP		
		
		ADD R3, R3, #-1
		BRp TRAVERSE
		BRnz READ		


CONTINUE_AST	ADD R0, R0, #-1
		ADD R7, R0, R7
		ADD R0, R0, #1
		BRnzp READ


CONTINUE	ADD R0, R0, #1
	BRnzp READ



DONE	ADD R0, R5, R0
PUTS

	HALT

ASCII_ZERO		.FILL x0030		;ASCII value of Zero
ASCII_NINE		.FILL x0039		;ASCII value of Nine
ASCII_NEG_ASTERISK   	.FILL xFFD6  		;negative of ascii value of *
ASCII_NEG_ZERO    	.FILL xFFD0		;negative of ascii value of 0
STRING_START 		.FILL x4000		;starting address of string
.END
